<?php

namespace Tests\Feature;

use Corals\User\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class PostsViewTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::query()->whereHas('roles', function ($query) {
            $query->where('name', 'superuser');
        })->first();
        Auth::loginUsingId($user->id);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_posts_view()
    {
        $response = $this->get('cms/posts');

        $response->assertStatus(200)->assertViewIs('cms::posts.index');
    }

    public function test_posts_create()
    {
        $response = $this->get('cms/posts/create');

        $response->assertViewIs('cms::posts.create_edit')->assertStatus(200);
    }

    public function test_posts_bulk_action()
    {
        $response = $this->post('cms/posts/bulk-action', [
            'action' => 'published',]);

        $response->assertSeeText('message');
    }
}
